version: 2

models:
  - name: stg_all_stations_data
    description: Dataset containing information about all the stations
    columns:
      - name: id
        tests:
          - not_null

  - name: stg_stations_details
    description: Dataset conatining the spaecific descriptions of each station
    columns:
      - name: id
        tests:
          - unique
          - not_null
     

  - name: stg_station_summary
    description: Dataset containing a summary of statistics about each station
    columns:
      - name: id
        tests:
          - unique
          - not_null
