version: 2

sources:
  - name: test
    description: A sample dataset from the datawarehouse project
    tables:
      - name: richards
        description: 'Details about the richards station'
      